"""Markdown report generator for GSC audit results."""

from models.audit_result import AuditResult
from models.data_shapes import METRIC_CATEGORIES


def generate_markdown_report(audit: AuditResult) -> str:
    """Generate a full Markdown report from audit results.

    Args:
        audit: Completed AuditResult.

    Returns:
        Markdown-formatted string.
    """
    lines = []

    # Header
    lines.append(f"# GSC Audit Report: {audit.property_url}")
    lines.append("")
    lines.append(
        f"**Date Range:** {audit.start_date} to {audit.end_date}"
    )
    lines.append(
        f"**Health Score:** {audit.health_score}/100 "
        f"(Grade: {audit.health_grade})"
    )
    lines.append(
        f"**Total Findings:** {audit.total_findings}"
    )
    lines.append(
        f"**Metrics Executed:** {len(audit.metrics_executed)}"
    )
    lines.append("")

    # Severity distribution
    lines.append("## Severity Distribution")
    lines.append("")
    for sev, count in audit.severity_counts.items():
        if count > 0:
            lines.append(f"- **{sev.title()}:** {count}")
    lines.append("")

    # Executive summary
    if audit.ai_executive_summary:
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(audit.ai_executive_summary)
        lines.append("")

    # Top findings
    top = audit.get_top_findings(10)
    if top:
        lines.append("## Top Findings")
        lines.append("")
        for i, r in enumerate(top, 1):
            lines.append(
                f"### {i}. {r.metric_name} "
                f"({r.severity.value.title()})"
            )
            lines.append("")
            lines.append(f"**Category:** {r.category}")
            lines.append(f"**Summary:** {r.summary}")
            if r.computed_value is not None:
                lines.append(
                    f"**Computed Value:** {r.computed_value:.2f}"
                )
            if r.affected_count > 0:
                lines.append(
                    f"**Affected Items:** "
                    f"{r.affected_count:,}"
                )
            if r.recommendations:
                lines.append("")
                lines.append("**Recommendations:**")
                for rec in r.recommendations:
                    lines.append(f"- {rec}")
            lines.append("")

    # Category details
    lines.append("## Category Analysis")
    lines.append("")

    for category in METRIC_CATEGORIES:
        cat_results = audit.results_by_category.get(
            category, []
        )
        if not cat_results:
            continue

        lines.append(f"### {category}")
        lines.append("")

        # AI narrative if available
        narrative = audit.ai_group_analyses.get(category)
        if narrative:
            lines.append(narrative)
            lines.append("")

        # Metric table
        lines.append(
            "| Metric | Severity | Value | "
            "Affected | Summary |"
        )
        lines.append(
            "|--------|----------|-------|"
            "----------|---------|"
        )

        for r in sorted(
            cat_results, key=lambda x: x.severity.priority
        ):
            val = (
                f"{r.computed_value:.2f}"
                if r.computed_value is not None
                else "—"
            )
            summary_short = r.summary[:60]
            if len(r.summary) > 60:
                summary_short += "..."
            lines.append(
                f"| {r.metric_name} | "
                f"{r.severity.value.title()} | "
                f"{val} | {r.affected_count:,} | "
                f"{summary_short} |"
            )
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(
        "*Generated by Ultimate GSC Auditor*"
    )

    return "\n".join(lines)
