"""Click & CTR metric group — metrics 13 through 21.

Analyses click distribution, CTR benchmarks, efficiency rates,
temporal deltas (MoM/YoY), CTR decay patterns, seasonality,
and portfolio concentration risk.
"""

import logging
from datetime import date, timedelta

import numpy as np
import pandas as pd

from metrics.base_metric import BaseMetricGroup
from models.metric_result import MetricResult, Severity, TrendDirection
from utils.benchmarks import compute_site_ctr_curve, get_expected_ctr, compute_ctr_gap

logger = logging.getLogger(__name__)


class ClickCTRMetrics(BaseMetricGroup):
    """Metrics 13-21: Click & CTR analysis."""

    METRIC_REGISTRY: dict[int, str] = {
        13: "click_share_per_url",
        14: "ctr_gap_score",
        15: "high_impression_zero_click_url_count",
        16: "click_efficiency_rate",
        17: "mom_click_delta",
        18: "yoy_click_delta",
        19: "ctr_decay_rate",
        20: "seasonal_click_index",
        21: "click_concentration_rate",
    }

    # ------------------------------------------------------------------
    # Metric 13 — Click Share per URL
    # ------------------------------------------------------------------
    def click_share_per_url(self) -> MetricResult:
        """Percentage of total site clicks generated by each URL."""
        df = self.get_df("page_90d")

        if df.empty or df["clicks"].sum() == 0:
            return self.create_result(
                metric_id=13,
                severity=Severity.INSIGHT,
                summary="No click data available to compute click share per URL.",
                recommendations=["Ensure the property has sufficient click data."],
            )

        total_clicks = df["clicks"].sum()
        page_clicks = (
            df.groupby("page")["clicks"]
            .sum()
            .reset_index()
            .rename(columns={"clicks": "clicks"})
        )
        page_clicks["click_share"] = page_clicks["clicks"] / total_clicks
        page_clicks = page_clicks.sort_values("click_share", ascending=False).reset_index(drop=True)

        top_url_share = page_clicks["click_share"].iloc[0] if len(page_clicks) > 0 else 0.0
        top_url = page_clicks["page"].iloc[0] if len(page_clicks) > 0 else ""

        # Determine severity based on top URL concentration
        if top_url_share > 0.50:
            severity = Severity.HIGH
            summary = (
                f"Extreme click concentration: the top URL captures "
                f"{top_url_share:.1%} of all clicks ({total_clicks:,} total). "
                f"Traffic is dangerously dependent on a single page."
            )
        elif top_url_share > 0.40:
            severity = Severity.MEDIUM
            summary = (
                f"High click concentration: the top URL captures "
                f"{top_url_share:.1%} of all clicks ({total_clicks:,} total). "
                f"Consider diversifying traffic sources."
            )
        elif top_url_share > 0.25:
            severity = Severity.LOW
            summary = (
                f"Moderate click concentration: the top URL captures "
                f"{top_url_share:.1%} of all clicks ({total_clicks:,} total)."
            )
        else:
            severity = Severity.INSIGHT
            summary = (
                f"Click distribution is healthy: the top URL captures "
                f"{top_url_share:.1%} of {total_clicks:,} total clicks."
            )

        # Build display table
        display_df = page_clicks.head(25).copy()
        display_df["click_share"] = display_df["click_share"].apply(
            lambda x: f"{x:.2%}"
        )
        display_df.columns = ["Page", "Clicks", "Click Share"]

        high_share_count = int((page_clicks["click_share"] > 0.05).sum())

        recommendations = []
        if top_url_share > 0.40:
            recommendations.append(
                f"The top URL ({top_url}) drives {top_url_share:.1%} of all clicks. "
                f"Diversify by improving underperforming pages with internal linking."
            )
        if high_share_count < 5:
            recommendations.append(
                f"Only {high_share_count} URLs generate >5% of total clicks. "
                f"Invest in building out more high-traffic pages to reduce risk."
            )
        recommendations.append(
            "Review low-click-share pages for title/meta description optimization "
            "to capture more clicks from their existing impressions."
        )

        return self.create_result(
            metric_id=13,
            severity=severity,
            summary=summary,
            computed_value=round(top_url_share * 100, 2),
            affected_count=len(page_clicks),
            data_table=display_df,
            recommendations=recommendations,
            details={
                "total_clicks": int(total_clicks),
                "url_count": len(page_clicks),
                "top_url": top_url,
                "top_url_share": round(top_url_share, 4),
            },
        )

    # ------------------------------------------------------------------
    # Metric 14 — CTR Gap Score
    # ------------------------------------------------------------------
    def ctr_gap_score(self) -> MetricResult:
        """Difference between actual CTR and expected benchmark CTR per query."""
        df = self.get_df("query_90d")

        if df.empty:
            return self.create_result(
                metric_id=14,
                severity=Severity.INSIGHT,
                summary="No query data available to compute CTR gap scores.",
                recommendations=["Ensure the property has sufficient query data."],
            )

        # Compute site-specific CTR curve
        ctr_curve = compute_site_ctr_curve(df)

        # Calculate expected and gap for each query
        working = df.copy()
        working["expected_ctr"] = working["position"].apply(
            lambda pos: get_expected_ctr(ctr_curve, pos)
        )
        working["ctr_gap"] = working.apply(
            lambda row: compute_ctr_gap(row["ctr"], row["expected_ctr"]),
            axis=1,
        )

        # Focus on queries with meaningful impressions
        significant = working[working["impressions"] >= 10].copy()

        if significant.empty:
            return self.create_result(
                metric_id=14,
                severity=Severity.INSIGHT,
                summary=(
                    "Not enough queries with 10+ impressions to compute "
                    "meaningful CTR gap scores."
                ),
                recommendations=["Wait for more data to accumulate."],
            )

        # Identify underperformers (negative gap, sorted worst first)
        underperformers = (
            significant[significant["ctr_gap"] < 0]
            .sort_values("ctr_gap")
            .copy()
        )

        # Weight severity by impression volume of underperformers
        total_impressions = significant["impressions"].sum()
        underperformer_impressions = underperformers["impressions"].sum()
        underperformer_share = (
            underperformer_impressions / total_impressions
            if total_impressions > 0
            else 0
        )

        # Median gap across all significant queries
        median_gap = significant["ctr_gap"].median()

        if median_gap < -0.05:
            severity = Severity.HIGH
            summary = (
                f"Site-wide CTR is significantly below its own benchmark curve. "
                f"Median CTR gap: {median_gap:.2%}. "
                f"{len(underperformers):,} queries underperform expectations "
                f"({underperformer_share:.0%} of impressions)."
            )
        elif median_gap < -0.02:
            severity = Severity.MEDIUM
            summary = (
                f"Moderate CTR underperformance detected. "
                f"Median CTR gap: {median_gap:.2%}. "
                f"{len(underperformers):,} queries fall below site benchmarks."
            )
        elif len(underperformers) > 0:
            severity = Severity.LOW
            summary = (
                f"Minor CTR optimization opportunities found. "
                f"Median CTR gap: {median_gap:+.2%}. "
                f"{len(underperformers):,} queries slightly underperform."
            )
        else:
            severity = Severity.INSIGHT
            summary = (
                f"CTR is at or above site benchmarks across all significant queries. "
                f"Median CTR gap: {median_gap:+.2%}."
            )

        # Build data table — top 25 underperformers sorted by impression weight
        if not underperformers.empty:
            table_df = (
                underperformers
                .sort_values(["impressions", "ctr_gap"], ascending=[False, True])
                .head(25)
                [["query", "position", "ctr", "expected_ctr", "ctr_gap", "impressions"]]
                .copy()
            )
            table_df["position"] = table_df["position"].round(1)
            table_df["ctr"] = table_df["ctr"].apply(lambda x: f"{x:.2%}")
            table_df["expected_ctr"] = table_df["expected_ctr"].apply(
                lambda x: f"{x:.2%}"
            )
            table_df["ctr_gap"] = table_df["ctr_gap"].apply(
                lambda x: f"{x:+.2%}"
            )
            table_df.columns = [
                "Query", "Position", "Actual CTR", "Expected CTR",
                "Gap", "Impressions",
            ]
        else:
            table_df = pd.DataFrame()

        recommendations = []
        if len(underperformers) > 0:
            top_opp = underperformers.head(1)
            if not top_opp.empty:
                top_query = top_opp["query"].iloc[0]
                recommendations.append(
                    f"Prioritize title/description optimization for '{top_query}' — "
                    f"it has the largest negative CTR gap weighted by impressions."
                )
        recommendations.append(
            "Review title tags and meta descriptions for underperforming queries. "
            "Use compelling language, numbers, and match search intent."
        )
        recommendations.append(
            "Consider adding structured data (FAQ, HowTo, Review) to boost "
            "rich snippet visibility and improve CTR."
        )

        return self.create_result(
            metric_id=14,
            severity=severity,
            summary=summary,
            computed_value=round(median_gap * 100, 2),
            affected_count=len(underperformers),
            data_table=table_df,
            recommendations=recommendations,
            benchmark_comparison="below" if median_gap < 0 else "above",
            details={
                "median_gap": round(median_gap, 4),
                "underperformer_count": len(underperformers),
                "underperformer_impression_share": round(underperformer_share, 4),
                "ctr_curve": {k: round(v, 4) for k, v in ctr_curve.items()},
            },
        )

    # ------------------------------------------------------------------
    # Metric 15 — High-Impression Zero-Click URL Count
    # ------------------------------------------------------------------
    def high_impression_zero_click_url_count(self) -> MetricResult:
        """URLs with >1000 impressions but 0 clicks — the most wasteful pages."""
        df = self.get_df("page_90d")

        if df.empty:
            return self.create_result(
                metric_id=15,
                severity=Severity.INSIGHT,
                summary="No page data available.",
                recommendations=["Ensure the property has page-level data."],
            )

        zero_click_high_imp = df[
            (df["impressions"] > 1000) & (df["clicks"] == 0)
        ].copy()

        total_urls = df["page"].nunique()
        count = len(zero_click_high_imp)
        wasted_impressions = (
            int(zero_click_high_imp["impressions"].sum())
            if count > 0
            else 0
        )

        if count >= 20:
            severity = Severity.CRITICAL
            summary = (
                f"{count} URLs have >1,000 impressions but ZERO clicks, "
                f"wasting {wasted_impressions:,} impressions. "
                f"These pages are visible but completely failing to attract clicks."
            )
        elif count >= 10:
            severity = Severity.HIGH
            summary = (
                f"{count} URLs have >1,000 impressions but zero clicks "
                f"({wasted_impressions:,} wasted impressions)."
            )
        elif count >= 5:
            severity = Severity.MEDIUM
            summary = (
                f"{count} URLs have >1,000 impressions but zero clicks "
                f"({wasted_impressions:,} wasted impressions)."
            )
        elif count >= 1:
            severity = Severity.LOW
            summary = (
                f"{count} URL(s) have >1,000 impressions but zero clicks "
                f"({wasted_impressions:,} wasted impressions)."
            )
        else:
            severity = Severity.INSIGHT
            summary = (
                "No high-impression zero-click URLs found. "
                "All well-visible pages are generating at least some clicks."
            )

        # Build table sorted by most wasted impressions
        if count > 0:
            table_df = (
                zero_click_high_imp
                .sort_values("impressions", ascending=False)
                .head(25)
                [["page", "impressions", "position"]]
                .copy()
            )
            table_df["position"] = table_df["position"].round(1)
            table_df.columns = ["Page", "Impressions", "Avg Position"]
        else:
            table_df = pd.DataFrame()

        recommendations = []
        if count > 0:
            recommendations.append(
                "Rewrite title tags and meta descriptions for these zero-click URLs. "
                "They are appearing in search results but failing to earn a single click."
            )
            recommendations.append(
                "Check average positions — if ranking on page 2+ the visibility "
                "may be too low for clicks. Focus on pushing to page 1."
            )
            recommendations.append(
                "Consider whether these pages match user intent. Pages ranking "
                "for mismatched queries will never earn clicks."
            )
        else:
            recommendations.append(
                "Keep monitoring as new pages get indexed. Aim to maintain "
                "zero high-impression zero-click URLs."
            )

        return self.create_result(
            metric_id=15,
            severity=severity,
            summary=summary,
            computed_value=float(count),
            affected_count=count,
            opportunity_value=f"{wasted_impressions:,} wasted impressions" if count > 0 else None,
            data_table=table_df,
            recommendations=recommendations,
            details={
                "zero_click_count": count,
                "total_urls": total_urls,
                "wasted_impressions": wasted_impressions,
            },
        )

    # ------------------------------------------------------------------
    # Metric 16 — Click Efficiency Rate
    # ------------------------------------------------------------------
    def click_efficiency_rate(self) -> MetricResult:
        """Clicks per 1,000 impressions (scaled CTR) by query."""
        df = self.get_df("query_90d")

        if df.empty or df["impressions"].sum() == 0:
            return self.create_result(
                metric_id=16,
                severity=Severity.INSIGHT,
                summary="No query data available to compute click efficiency.",
                recommendations=["Ensure the property has query-level data."],
            )

        total_clicks = df["clicks"].sum()
        total_impressions = df["impressions"].sum()
        site_efficiency = (total_clicks / total_impressions) * 1000

        # Per-query efficiency
        working = df[df["impressions"] > 0].copy()
        working["efficiency"] = (working["clicks"] / working["impressions"]) * 1000

        # Overall site benchmark
        if site_efficiency >= 80:
            severity = Severity.INSIGHT
            summary = (
                f"Site-wide click efficiency is strong at {site_efficiency:.1f} "
                f"clicks per 1,000 impressions ({total_clicks:,} clicks / "
                f"{total_impressions:,} impressions)."
            )
        elif site_efficiency >= 40:
            severity = Severity.LOW
            summary = (
                f"Site-wide click efficiency is moderate at {site_efficiency:.1f} "
                f"clicks per 1,000 impressions."
            )
        elif site_efficiency >= 15:
            severity = Severity.MEDIUM
            summary = (
                f"Site-wide click efficiency is below average at {site_efficiency:.1f} "
                f"clicks per 1,000 impressions. There is meaningful room to improve CTR."
            )
        else:
            severity = Severity.HIGH
            summary = (
                f"Site-wide click efficiency is poor at {site_efficiency:.1f} "
                f"clicks per 1,000 impressions. Most impressions are not converting to clicks."
            )

        # Top and bottom performing queries
        high_imp = working[working["impressions"] >= 50].copy()
        if not high_imp.empty:
            worst_queries = high_imp.nsmallest(25, "efficiency")
            table_df = worst_queries[
                ["query", "clicks", "impressions", "efficiency", "position"]
            ].copy()
            table_df["efficiency"] = table_df["efficiency"].round(1)
            table_df["position"] = table_df["position"].round(1)
            table_df.columns = [
                "Query", "Clicks", "Impressions",
                "Efficiency (per 1K)", "Avg Position",
            ]
        else:
            table_df = pd.DataFrame()

        # Count of highly inefficient queries (< 5 clicks per 1K impressions)
        inefficient_count = int(
            (high_imp["efficiency"] < 5).sum()
        ) if not high_imp.empty else 0

        recommendations = [
            "Focus on the least efficient high-impression queries in the table. "
            "Improving their title tags and meta descriptions can yield quick wins.",
        ]
        if site_efficiency < 40:
            recommendations.append(
                "A site-wide efficiency below 40/1K suggests systematic CTR issues. "
                "Audit SERP snippets, check for cannibalization, and ensure "
                "search intent alignment."
            )
        recommendations.append(
            "Compare efficiency across position ranges — low efficiency at "
            "positions 1-3 signals poor snippet appeal, while low efficiency "
            "at positions 4-10 is more expected."
        )

        return self.create_result(
            metric_id=16,
            severity=severity,
            summary=summary,
            computed_value=round(site_efficiency, 2),
            affected_count=inefficient_count,
            data_table=table_df,
            recommendations=recommendations,
            details={
                "site_efficiency": round(site_efficiency, 2),
                "total_clicks": int(total_clicks),
                "total_impressions": int(total_impressions),
                "inefficient_query_count": inefficient_count,
            },
        )

    # ------------------------------------------------------------------
    # Metric 17 — MoM Click Delta (%)
    # ------------------------------------------------------------------
    def mom_click_delta(self) -> MetricResult:
        """Percentage change in clicks per URL, month over month."""
        df_90d = self.get_df("page_date_90d")
        df_30d = self.get_df("page_date_30d")

        if df_90d.empty and df_30d.empty:
            return self.create_result(
                metric_id=17,
                severity=Severity.INSIGHT,
                summary="No temporal page data available for MoM comparison.",
                recommendations=["Ensure page_date_90d and page_date_30d shapes are fetched."],
            )

        # Combine data and parse dates
        combined = pd.concat([df_90d, df_30d], ignore_index=True)
        if combined.empty or "date" not in combined.columns:
            return self.create_result(
                metric_id=17,
                severity=Severity.INSIGHT,
                summary="Insufficient date data for MoM click comparison.",
                recommendations=["Verify that date-dimension data is available."],
            )

        combined["date"] = pd.to_datetime(combined["date"])

        # Determine current 30d and previous 30d boundaries
        max_date = combined["date"].max()
        current_start = max_date - timedelta(days=29)
        previous_end = current_start - timedelta(days=1)
        previous_start = previous_end - timedelta(days=29)

        current_mask = (combined["date"] >= current_start) & (combined["date"] <= max_date)
        previous_mask = (combined["date"] >= previous_start) & (combined["date"] <= previous_end)

        current_clicks = (
            combined[current_mask]
            .groupby("page")["clicks"]
            .sum()
            .rename("current_clicks")
        )
        previous_clicks = (
            combined[previous_mask]
            .groupby("page")["clicks"]
            .sum()
            .rename("previous_clicks")
        )

        merged = pd.merge(
            current_clicks, previous_clicks,
            left_index=True, right_index=True, how="outer",
        ).fillna(0)

        # Avoid division by zero: only compute delta where previous > 0
        merged["delta_pct"] = np.where(
            merged["previous_clicks"] > 0,
            ((merged["current_clicks"] - merged["previous_clicks"])
             / merged["previous_clicks"]) * 100,
            np.where(merged["current_clicks"] > 0, np.inf, 0.0),
        )

        # Replace inf with a large sentinel for sorting, then filter finite
        finite = merged[np.isfinite(merged["delta_pct"])].copy()

        # Significant decliners (>20% drop)
        decliners = finite[finite["delta_pct"] < -20].sort_values("delta_pct")
        gainers = finite[finite["delta_pct"] > 20].sort_values(
            "delta_pct", ascending=False
        )

        total_current = merged["current_clicks"].sum()
        total_previous = merged["previous_clicks"].sum()
        overall_delta = (
            ((total_current - total_previous) / total_previous) * 100
            if total_previous > 0
            else 0.0
        )

        # Determine trend
        if overall_delta > 5:
            trend = TrendDirection.IMPROVING
        elif overall_delta < -5:
            trend = TrendDirection.DECLINING
        else:
            trend = TrendDirection.STABLE

        # Severity based on decline count and magnitude
        decline_count = len(decliners)
        if overall_delta < -20:
            severity = Severity.CRITICAL
            summary = (
                f"Site-wide clicks declined {overall_delta:.1f}% month over month. "
                f"{decline_count} URLs dropped >20%."
            )
        elif overall_delta < -10:
            severity = Severity.HIGH
            summary = (
                f"Site-wide clicks declined {overall_delta:.1f}% MoM. "
                f"{decline_count} URLs dropped >20%."
            )
        elif decline_count > 10:
            severity = Severity.MEDIUM
            summary = (
                f"Site-wide clicks changed {overall_delta:+.1f}% MoM, but "
                f"{decline_count} individual URLs dropped >20%."
            )
        elif decline_count > 0:
            severity = Severity.LOW
            summary = (
                f"Site-wide clicks changed {overall_delta:+.1f}% MoM. "
                f"{decline_count} URL(s) declined >20%."
            )
        else:
            severity = Severity.INSIGHT
            summary = (
                f"Site-wide clicks changed {overall_delta:+.1f}% MoM. "
                f"No significant per-URL declines detected."
            )

        # Build data table — biggest decliners
        if not decliners.empty:
            table_df = decliners.head(25).reset_index()
            table_df["delta_pct"] = table_df["delta_pct"].round(1)
            table_df["current_clicks"] = table_df["current_clicks"].astype(int)
            table_df["previous_clicks"] = table_df["previous_clicks"].astype(int)
            table_df.columns = [
                "Page", "Current Clicks (30d)",
                "Previous Clicks (30d)", "Change %",
            ]
        else:
            table_df = pd.DataFrame()

        recommendations = []
        if decline_count > 0:
            recommendations.append(
                f"{decline_count} URLs lost >20% of clicks MoM. "
                f"Investigate whether positions dropped, impressions fell, "
                f"or CTR degraded for each."
            )
        if overall_delta < -10:
            recommendations.append(
                "A site-wide click decline of this magnitude may indicate "
                "an algorithm update impact, seasonal shift, or technical issue. "
                "Check Google Search Status Dashboard and server logs."
            )
        recommendations.append(
            "Cross-reference declining URLs with position changes (metric 28) "
            "to separate ranking-driven drops from CTR-driven drops."
        )

        return self.create_result(
            metric_id=17,
            severity=severity,
            summary=summary,
            computed_value=round(overall_delta, 2),
            affected_count=decline_count,
            data_table=table_df,
            recommendations=recommendations,
            trend_direction=trend,
            details={
                "overall_delta_pct": round(overall_delta, 2),
                "total_current_clicks": int(total_current),
                "total_previous_clicks": int(total_previous),
                "decline_count": decline_count,
                "gain_count": len(gainers),
            },
        )

    # ------------------------------------------------------------------
    # Metric 18 — YoY Click Delta (%)
    # ------------------------------------------------------------------
    def yoy_click_delta(self) -> MetricResult:
        """Percentage change in clicks per URL, year over year."""
        df_90d = self.get_df("page_date_90d")
        df_365d = self.get_df("page_date_365d")

        if df_365d.empty:
            return self.create_result(
                metric_id=18,
                severity=Severity.INSIGHT,
                summary="No 365-day data available for YoY comparison.",
                recommendations=[
                    "YoY analysis requires page_date_365d data. "
                    "The property may not have a full year of data."
                ],
            )

        # Combine and parse dates
        combined = pd.concat([df_90d, df_365d], ignore_index=True)
        combined["date"] = pd.to_datetime(combined["date"])

        # Define current 90d and prior-year 90d ranges
        max_date = combined["date"].max()
        current_start = max_date - timedelta(days=89)
        yoy_end = current_start.replace(year=current_start.year - 1) + timedelta(days=89)
        yoy_start = current_start.replace(year=current_start.year - 1)

        # Handle leap year edge cases
        try:
            yoy_end = max_date.replace(year=max_date.year - 1)
            yoy_start = current_start.replace(year=current_start.year - 1)
        except ValueError:
            # Feb 29 -> Feb 28
            yoy_end = max_date.replace(year=max_date.year - 1, day=28)
            yoy_start = current_start.replace(year=current_start.year - 1, day=28)

        current_mask = (combined["date"] >= current_start) & (combined["date"] <= max_date)
        yoy_mask = (combined["date"] >= yoy_start) & (combined["date"] <= yoy_end)

        current_clicks = (
            combined[current_mask]
            .groupby("page")["clicks"]
            .sum()
            .rename("current_clicks")
        )
        yoy_clicks = (
            combined[yoy_mask]
            .groupby("page")["clicks"]
            .sum()
            .rename("yoy_clicks")
        )

        if yoy_clicks.empty or yoy_clicks.sum() == 0:
            return self.create_result(
                metric_id=18,
                severity=Severity.INSIGHT,
                summary=(
                    "No prior-year click data found for the comparison window. "
                    "The property may be less than a year old."
                ),
                recommendations=[
                    "YoY comparisons need at least 12 months of data. "
                    "Revisit this metric once more historical data is available."
                ],
            )

        merged = pd.merge(
            current_clicks, yoy_clicks,
            left_index=True, right_index=True, how="outer",
        ).fillna(0)

        merged["delta_pct"] = np.where(
            merged["yoy_clicks"] > 0,
            ((merged["current_clicks"] - merged["yoy_clicks"])
             / merged["yoy_clicks"]) * 100,
            np.where(merged["current_clicks"] > 0, np.inf, 0.0),
        )

        finite = merged[np.isfinite(merged["delta_pct"])].copy()

        # Significant decliners (>30% drop)
        decliners = finite[finite["delta_pct"] < -30].sort_values("delta_pct")

        total_current = merged["current_clicks"].sum()
        total_yoy = merged["yoy_clicks"].sum()
        overall_delta = (
            ((total_current - total_yoy) / total_yoy) * 100
            if total_yoy > 0
            else 0.0
        )

        if overall_delta > 5:
            trend = TrendDirection.IMPROVING
        elif overall_delta < -5:
            trend = TrendDirection.DECLINING
        else:
            trend = TrendDirection.STABLE

        decline_count = len(decliners)

        if overall_delta < -30:
            severity = Severity.CRITICAL
            summary = (
                f"Site-wide clicks declined {overall_delta:.1f}% year over year. "
                f"{decline_count} URLs dropped >30%. "
                f"This represents a major traffic regression."
            )
        elif overall_delta < -15:
            severity = Severity.HIGH
            summary = (
                f"Site-wide clicks declined {overall_delta:.1f}% YoY. "
                f"{decline_count} URLs dropped >30%."
            )
        elif decline_count > 15:
            severity = Severity.MEDIUM
            summary = (
                f"Site-wide clicks changed {overall_delta:+.1f}% YoY, but "
                f"{decline_count} URLs lost >30% of clicks."
            )
        elif decline_count > 0:
            severity = Severity.LOW
            summary = (
                f"Site-wide clicks changed {overall_delta:+.1f}% YoY. "
                f"{decline_count} URL(s) declined >30%."
            )
        else:
            severity = Severity.INSIGHT
            summary = (
                f"Site-wide clicks changed {overall_delta:+.1f}% YoY. "
                f"No significant per-URL declines (>30%) detected."
            )

        # Table
        if not decliners.empty:
            table_df = decliners.head(25).reset_index()
            table_df["delta_pct"] = table_df["delta_pct"].round(1)
            table_df["current_clicks"] = table_df["current_clicks"].astype(int)
            table_df["yoy_clicks"] = table_df["yoy_clicks"].astype(int)
            table_df.columns = [
                "Page", "Current Clicks (90d)",
                "Prior Year Clicks (90d)", "Change %",
            ]
        else:
            table_df = pd.DataFrame()

        recommendations = []
        if decline_count > 0:
            recommendations.append(
                f"{decline_count} URLs lost >30% of clicks YoY. Determine if this "
                f"is due to ranking loss, content staleness, or increased competition."
            )
        if overall_delta < -15:
            recommendations.append(
                "A double-digit YoY decline indicates structural issues. "
                "Audit top declining pages for outdated content, broken links, "
                "and competitive SERP changes."
            )
        recommendations.append(
            "Compare YoY click trends with impression trends (metric 23) "
            "to isolate whether the issue is visibility loss or CTR decay."
        )

        return self.create_result(
            metric_id=18,
            severity=severity,
            summary=summary,
            computed_value=round(overall_delta, 2),
            affected_count=decline_count,
            data_table=table_df,
            recommendations=recommendations,
            trend_direction=trend,
            details={
                "overall_delta_pct": round(overall_delta, 2),
                "total_current_clicks": int(total_current),
                "total_yoy_clicks": int(total_yoy),
                "decline_count": decline_count,
            },
        )

    # ------------------------------------------------------------------
    # Metric 19 — CTR Decay Rate
    # ------------------------------------------------------------------
    def ctr_decay_rate(self) -> MetricResult:
        """Rate at which CTR drops as position worsens (bucket analysis)."""
        df = self.get_df("query_90d")

        if df.empty:
            return self.create_result(
                metric_id=19,
                severity=Severity.INSIGHT,
                summary="No query data available to compute CTR decay rate.",
                recommendations=["Ensure query-level data is available."],
            )

        # Filter to queries with meaningful impressions
        working = df[df["impressions"] >= 10].copy()
        if working.empty:
            return self.create_result(
                metric_id=19,
                severity=Severity.INSIGHT,
                summary="Not enough queries with 10+ impressions for decay analysis.",
                recommendations=["Wait for more data to accumulate."],
            )

        # Assign position buckets
        def _bucket(pos: float) -> str:
            if pos <= 3:
                return "1-3"
            elif pos <= 7:
                return "4-7"
            elif pos <= 10:
                return "8-10"
            elif pos <= 20:
                return "11-20"
            else:
                return "21+"

        working["bucket"] = working["position"].apply(_bucket)

        # Weighted average CTR per bucket (weighted by impressions)
        bucket_stats = (
            working.groupby("bucket")
            .apply(
                lambda g: pd.Series({
                    "avg_ctr": np.average(g["ctr"], weights=g["impressions"])
                    if g["impressions"].sum() > 0 else 0.0,
                    "query_count": len(g),
                    "total_impressions": g["impressions"].sum(),
                }),
            )
            .reset_index()
        )

        # Ensure bucket ordering
        bucket_order = ["1-3", "4-7", "8-10", "11-20", "21+"]
        bucket_stats["bucket"] = pd.Categorical(
            bucket_stats["bucket"], categories=bucket_order, ordered=True,
        )
        bucket_stats = bucket_stats.sort_values("bucket").reset_index(drop=True)

        # Compute decay ratios between adjacent buckets
        decay_ratios = []
        for i in range(len(bucket_stats) - 1):
            ctr_upper = bucket_stats.iloc[i]["avg_ctr"]
            ctr_lower = bucket_stats.iloc[i + 1]["avg_ctr"]
            if ctr_upper > 0:
                ratio = ctr_lower / ctr_upper
                decay_ratios.append({
                    "from_bucket": bucket_stats.iloc[i]["bucket"],
                    "to_bucket": bucket_stats.iloc[i + 1]["bucket"],
                    "from_ctr": ctr_upper,
                    "to_ctr": ctr_lower,
                    "decay_ratio": ratio,
                })

        # Average decay ratio
        avg_decay = (
            np.mean([d["decay_ratio"] for d in decay_ratios])
            if decay_ratios
            else 1.0
        )

        # Steeper decay (lower ratio) means more position-sensitive
        if avg_decay < 0.30:
            severity = Severity.HIGH
            summary = (
                f"Very steep CTR decay (avg ratio: {avg_decay:.2f}). "
                f"CTR drops dramatically between position buckets — "
                f"even small position changes have outsized click impact."
            )
        elif avg_decay < 0.50:
            severity = Severity.MEDIUM
            summary = (
                f"Moderate CTR decay rate (avg ratio: {avg_decay:.2f}). "
                f"Position improvements will yield meaningful CTR gains."
            )
        elif avg_decay < 0.70:
            severity = Severity.LOW
            summary = (
                f"Gradual CTR decay (avg ratio: {avg_decay:.2f}). "
                f"CTR decreases moderately across position buckets."
            )
        else:
            severity = Severity.INSIGHT
            summary = (
                f"Flat CTR curve (avg ratio: {avg_decay:.2f}). "
                f"CTR is relatively stable across positions, which may indicate "
                f"strong brand recognition or niche-specific search behavior."
            )

        # Build display table
        display_data = bucket_stats.copy()
        display_data["avg_ctr"] = display_data["avg_ctr"].apply(
            lambda x: f"{x:.2%}"
        )
        display_data["query_count"] = display_data["query_count"].astype(int)
        display_data["total_impressions"] = display_data["total_impressions"].astype(int)
        display_data.columns = [
            "Position Bucket", "Avg CTR", "Query Count", "Total Impressions",
        ]

        recommendations = []
        if avg_decay < 0.50:
            recommendations.append(
                "The steep CTR decay means position 1-3 rankings are "
                "disproportionately valuable. Prioritize pushing position 4-7 "
                "queries into the top 3."
            )
        recommendations.append(
            "Queries in the 4-7 range represent the highest-leverage "
            "optimization targets — small ranking improvements yield "
            "large CTR gains due to the decay curve."
        )
        recommendations.append(
            "Compare this decay rate against the site-specific CTR curve "
            "(metric 14) to identify individual query outliers."
        )

        return self.create_result(
            metric_id=19,
            severity=severity,
            summary=summary,
            computed_value=round(avg_decay, 4),
            affected_count=len(working),
            data_table=display_data,
            recommendations=recommendations,
            details={
                "avg_decay_ratio": round(avg_decay, 4),
                "decay_steps": decay_ratios,
                "bucket_count": len(bucket_stats),
            },
        )

    # ------------------------------------------------------------------
    # Metric 20 — Seasonal Click Index
    # ------------------------------------------------------------------
    def seasonal_click_index(self) -> MetricResult:
        """Ratio of current-month clicks vs same month in prior year."""
        df = self.get_df("page_date_365d")

        if df.empty or "date" not in df.columns:
            return self.create_result(
                metric_id=20,
                severity=Severity.INSIGHT,
                summary="No 365-day page data available for seasonal comparison.",
                recommendations=[
                    "This metric requires page_date_365d data spanning at least "
                    "12 months."
                ],
            )

        df = df.copy()
        df["date"] = pd.to_datetime(df["date"])

        max_date = df["date"].max()
        current_start = max_date - timedelta(days=29)

        # Current 30-day window
        current_mask = (df["date"] >= current_start) & (df["date"] <= max_date)
        current_clicks = df[current_mask]["clicks"].sum()

        # Same 30-day window last year
        try:
            yoy_end = max_date.replace(year=max_date.year - 1)
            yoy_start = current_start.replace(year=current_start.year - 1)
        except ValueError:
            yoy_end = max_date.replace(year=max_date.year - 1, day=28)
            yoy_start = current_start.replace(year=current_start.year - 1, day=28)

        yoy_mask = (df["date"] >= yoy_start) & (df["date"] <= yoy_end)
        yoy_clicks = df[yoy_mask]["clicks"].sum()

        if yoy_clicks == 0:
            return self.create_result(
                metric_id=20,
                severity=Severity.INSIGHT,
                summary=(
                    "No clicks found for the same period last year. "
                    "The property may be less than a year old or had no traffic."
                ),
                computed_value=None,
                recommendations=[
                    "Seasonal indexing requires a full year of historical data."
                ],
            )

        seasonal_index = current_clicks / yoy_clicks

        # Per-page seasonal indices
        page_current = (
            df[current_mask]
            .groupby("page")["clicks"]
            .sum()
            .rename("current_clicks")
        )
        page_yoy = (
            df[yoy_mask]
            .groupby("page")["clicks"]
            .sum()
            .rename("yoy_clicks")
        )
        page_merged = pd.merge(
            page_current, page_yoy,
            left_index=True, right_index=True, how="outer",
        ).fillna(0)

        page_merged["seasonal_index"] = np.where(
            page_merged["yoy_clicks"] > 0,
            page_merged["current_clicks"] / page_merged["yoy_clicks"],
            np.where(page_merged["current_clicks"] > 0, np.inf, 0.0),
        )

        finite_pages = page_merged[np.isfinite(page_merged["seasonal_index"])].copy()
        declining_pages = finite_pages[finite_pages["seasonal_index"] < 0.7]
        decline_count = len(declining_pages)

        # Determine trend and severity
        if seasonal_index > 1.05:
            trend = TrendDirection.IMPROVING
        elif seasonal_index < 0.95:
            trend = TrendDirection.DECLINING
        else:
            trend = TrendDirection.STABLE

        if seasonal_index < 0.5:
            severity = Severity.CRITICAL
            summary = (
                f"Seasonal Click Index: {seasonal_index:.2f} — clicks are at "
                f"less than half of last year's level for this period. "
                f"({current_clicks:,} vs {yoy_clicks:,})."
            )
        elif seasonal_index < 0.7:
            severity = Severity.HIGH
            summary = (
                f"Seasonal Click Index: {seasonal_index:.2f} — clicks are "
                f"significantly below last year ({current_clicks:,} vs {yoy_clicks:,})."
            )
        elif seasonal_index < 0.9:
            severity = Severity.MEDIUM
            summary = (
                f"Seasonal Click Index: {seasonal_index:.2f} — clicks are "
                f"moderately below last year ({current_clicks:,} vs {yoy_clicks:,})."
            )
        elif seasonal_index <= 1.1:
            severity = Severity.INSIGHT
            summary = (
                f"Seasonal Click Index: {seasonal_index:.2f} — clicks are "
                f"stable compared to last year ({current_clicks:,} vs {yoy_clicks:,})."
            )
        else:
            severity = Severity.INSIGHT
            summary = (
                f"Seasonal Click Index: {seasonal_index:.2f} — clicks are "
                f"growing compared to last year ({current_clicks:,} vs {yoy_clicks:,})."
            )

        # Table: pages with biggest seasonal dips
        if not declining_pages.empty:
            table_df = (
                declining_pages
                .sort_values("seasonal_index")
                .head(25)
                .reset_index()
            )
            table_df["current_clicks"] = table_df["current_clicks"].astype(int)
            table_df["yoy_clicks"] = table_df["yoy_clicks"].astype(int)
            table_df["seasonal_index"] = table_df["seasonal_index"].round(2)
            table_df.columns = [
                "Page", "Current Clicks (30d)",
                "Same Period Last Year", "Seasonal Index",
            ]
        else:
            table_df = pd.DataFrame()

        recommendations = []
        if seasonal_index < 0.9:
            recommendations.append(
                "Clicks are below last year's seasonal baseline. Determine "
                "whether this is a genuine seasonal pattern or a traffic loss. "
                "Compare impression trends (metric 23) to isolate the cause."
            )
        if decline_count > 5:
            recommendations.append(
                f"{decline_count} pages show a seasonal index below 0.7. "
                f"Refresh content on these pages with updated dates, "
                f"new data, and current information."
            )
        recommendations.append(
            "Build a seasonal content calendar based on this data. "
            "Pages that consistently dip at certain times of year may "
            "benefit from seasonal updates or evergreen rewrites."
        )

        return self.create_result(
            metric_id=20,
            severity=severity,
            summary=summary,
            computed_value=round(seasonal_index, 4),
            affected_count=decline_count,
            data_table=table_df,
            recommendations=recommendations,
            trend_direction=trend,
            details={
                "seasonal_index": round(seasonal_index, 4),
                "current_clicks": int(current_clicks),
                "yoy_clicks": int(yoy_clicks),
                "declining_page_count": decline_count,
            },
        )

    # ------------------------------------------------------------------
    # Metric 21 — Click Concentration Rate
    # ------------------------------------------------------------------
    def click_concentration_rate(self) -> MetricResult:
        """Percentage of total site clicks coming from top 10% of URLs."""
        df = self.get_df("page_90d")

        if df.empty or df["clicks"].sum() == 0:
            return self.create_result(
                metric_id=21,
                severity=Severity.INSIGHT,
                summary="No click data available to compute concentration.",
                recommendations=["Ensure page-level click data is available."],
            )

        total_clicks = df["clicks"].sum()
        page_clicks = (
            df.groupby("page")["clicks"]
            .sum()
            .sort_values(ascending=False)
            .reset_index()
        )

        total_urls = len(page_clicks)
        top_10pct_count = max(1, int(np.ceil(total_urls * 0.10)))
        top_10pct = page_clicks.head(top_10pct_count)
        top_10pct_clicks = top_10pct["clicks"].sum()
        concentration_rate = top_10pct_clicks / total_clicks

        if concentration_rate > 0.90:
            severity = Severity.HIGH
            summary = (
                f"Extreme click concentration: the top 10% of URLs "
                f"({top_10pct_count} pages) capture {concentration_rate:.1%} "
                f"of all {total_clicks:,} clicks. This is a significant "
                f"portfolio risk."
            )
        elif concentration_rate > 0.80:
            severity = Severity.MEDIUM
            summary = (
                f"High click concentration: the top 10% of URLs "
                f"({top_10pct_count} pages) capture {concentration_rate:.1%} "
                f"of all {total_clicks:,} clicks."
            )
        elif concentration_rate > 0.65:
            severity = Severity.LOW
            summary = (
                f"Moderate click concentration: the top 10% of URLs "
                f"({top_10pct_count} pages) capture {concentration_rate:.1%} "
                f"of all {total_clicks:,} clicks."
            )
        else:
            severity = Severity.INSIGHT
            summary = (
                f"Healthy click distribution: the top 10% of URLs "
                f"({top_10pct_count} pages) capture {concentration_rate:.1%} "
                f"of all {total_clicks:,} clicks."
            )

        # Also compute top 1%, top 5%, top 20% for context
        top_1pct_count = max(1, int(np.ceil(total_urls * 0.01)))
        top_5pct_count = max(1, int(np.ceil(total_urls * 0.05)))
        top_20pct_count = max(1, int(np.ceil(total_urls * 0.20)))

        distribution = {
            "Top 1%": page_clicks.head(top_1pct_count)["clicks"].sum() / total_clicks,
            "Top 5%": page_clicks.head(top_5pct_count)["clicks"].sum() / total_clicks,
            "Top 10%": concentration_rate,
            "Top 20%": page_clicks.head(top_20pct_count)["clicks"].sum() / total_clicks,
        }

        dist_df = pd.DataFrame([
            {
                "Segment": k,
                "URL Count": {
                    "Top 1%": top_1pct_count,
                    "Top 5%": top_5pct_count,
                    "Top 10%": top_10pct_count,
                    "Top 20%": top_20pct_count,
                }[k],
                "Click Share": f"{v:.1%}",
                "Clicks": int(v * total_clicks),
            }
            for k, v in distribution.items()
        ])

        recommendations = []
        if concentration_rate > 0.80:
            recommendations.append(
                "Over 80% of clicks come from just 10% of pages. If any of "
                "these top pages lose rankings, traffic will drop significantly. "
                "Diversify by building more high-quality content."
            )
            recommendations.append(
                "Identify the specific pages in the top 10% and create "
                "supporting content clusters around them to build resilience."
            )
        recommendations.append(
            "Review underperforming pages (bottom 90%) for optimization "
            "opportunities — improved titles, internal linking, and content "
            "updates can shift more clicks to the long tail."
        )

        return self.create_result(
            metric_id=21,
            severity=severity,
            summary=summary,
            computed_value=round(concentration_rate * 100, 2),
            affected_count=top_10pct_count,
            data_table=dist_df,
            recommendations=recommendations,
            details={
                "concentration_rate": round(concentration_rate, 4),
                "top_10pct_count": top_10pct_count,
                "total_urls": total_urls,
                "total_clicks": int(total_clicks),
                "distribution": {
                    k: round(v, 4) for k, v in distribution.items()
                },
            },
        )
